 # This file has been copied from CiteWorth. All credit goes to them.
 # Original file: https://github.com/copenlu/cite-worth/blob/main/dataset_creation/data/permissible_section_titles.txt
- introduction
- abstract
- method
- methods
- results
- discussion
- discussions
- conclusion
- conclusions
- results and discussion
- related work
- experimental results
- literature review
- experiments
- background
- methodology
- conclusions and future work
- related works
- limitations
- procedure
- material and methods
- discussion and conclusion
- implementation
- evaluation
- performance evaluation
- experiments and results
- overview
- experimental design
- discussion and conclusions
- results and discussions
- motivation
- proposed method
- analysis
- future work
- results and analysis
- implementation details
