columns_to_keep: # order is also applied
  - paper_index
  - split  # manual 80/10/10 split
  - section_index  # to change context length in the future
  - section_category
  - text_index  # to keep order for context length
  - text
  - label

rename_columns:
  # original_name: target_name
  paper_id: paper_index
  sentences: text